### ISSUE TITLE
Add pjsip

### ISSUE THREAD

**Issue by stefan-langenmaier** [stefan-langenmaier/ring-overlay#11]
ring daemon uses now pjproject-2.5.5 and there is version 2.5.2 already in portage

**Comment by YogSottot** [comment]
There is [PJSIP version 2.6 is released](https://blog.pjsip.org/2017/01/26/pjsip-version-2-6-is-released-with-uwp-wp8-x-support/)

```
As usual the release also includes several enhancements and bug fixes: 
adding AES-GCM SRTP cipher-suites, 
OpenH264 1.6.0 support, 
OpenSSL 1.1.0 support, 
critical bug fixes in IPv6, ICE, and DNS resolver.
```

**Comment by stefan-langenmaier** [comment]
Thanks for the update. At the moment the `system-pjproject` use flag is very experimental. As the bundled version contains some patches, e.g. for gnutls support.

I'll try to include theses patches first.

For a general update of pjproject it might also be a good idea to write a bug report directly in the Gentoo bug tracker.

**Comment by YogSottot** [comment]
All patches available in ring-project/daemon/contrib/src/pjproject/
Seems that upstream do not want to add this patches http://lists.pjsip.org/pipermail/pjsip_lists.pjsip.org/2016-April/019197.html

**Comment by stefan-langenmaier** [comment]
Yes I also doubt that the patches will be included in the near future.

I haven't had the time to include the patches in the ebuild included in this repository. Patches welcome. :)
