### ISSUE TITLE
Setting S variable in ring-daemon-99999999 is redundant

### ISSUE THREAD

**Issue by gedia** [stefan-langenmaier/ring-overlay#12]
Setting the S variable to "${WORKDIR}/ring-project/daemon/" in ring-daemon-99999999 seems to be redundant (and wrong). In my case, source was made available under /var/tmp/portage/net-voip/ring-daemon-99999999/work/ring-daemon-99999999/.

**Comment by stefan-langenmaier** [comment]
Thanks for the report. I recently "merged" the live ebuilds and the stable ones, to bump them easier. For the stable ebuilds this is necessary. This should be fixed in the latest commit.
