### ISSUE TITLE
src_configure will always fail for ring-daemon-99999999 if system-asio USE flag is set

### ISSUE THREAD

**Issue by gedia** [stefan-langenmaier/ring-overlay#13]
To quote from the ebuild:

```
        if use system-asio; then
                die "asio blocked by restbed"
                rm -r src/asio
                sed -i.bak 's/^DEPS_\(.*\) = \(.*\)asio\(.*\)/DEPS_\1 = \2 \3/g' src/*/rules.mak
        fi
```

Is this intentional? Is it because restbed seems to still be in the TODO bucket as a dependency?

**Comment by stefan-langenmaier** [comment]
Yes it's intentional, I'm not completely done how I want the use flags to behave and this is supposed to be a short term fix.
Technically it should to be possible to build with an external asio, but I haven't worked out the problem with restbed.
I leave the issue open till it's done.

**Comment by stefan-langenmaier** [comment]
The use flags got their major overhaul.

asio is now always unbundled and restbed can be configured as needed.
