### ISSUE TITLE
undefined symbol: _ZN6Person9callAddedEP4Call

### ISSUE THREAD

**Issue by josiah47** [stefan-langenmaier/ring-overlay#14]
I have successfully compiled gnome-ring, but when I go to start I get this.
`gnome-ring: symbol lookup error: gnome-ring: undefined symbol: _ZN6Person9callAddedEP4Call`

strace ring provides this

> execve("/usr/bin/ring", ["ring"], [/* 45 vars */]) = 0
brk(NULL)                               = 0x18d7000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe99d4aa000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=159933, ...}) = 0
mmap(NULL, 159933, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fe99d479000
close(3)                                = 0
open("/lib64/libreadline.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220e\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0555, st_size=296856, ...}) = 0
mmap(NULL, 2398136, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fe99d031000
mprotect(0x7fe99d071000, 2097152, PROT_NONE) = 0
mmap(0x7fe99d271000, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x40000) = 0x7fe99d271000
mmap(0x7fe99d27a000, 1976, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fe99d27a000
close(3)                                = 0
open("/lib64/libncurses.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320Y\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=378584, ...}) = 0
mmap(NULL, 2476432, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fe99cdd1000
mprotect(0x7fe99ce29000, 2093056, PROT_NONE) = 0
mmap(0x7fe99d028000, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x57000) = 0x7fe99d028000
mmap(0x7fe99d02d000, 2448, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fe99d02d000
close(3)                                = 0
open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320\10\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1656648, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe99d4a9000
mmap(NULL, 3763608, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fe99ca39000
mprotect(0x7fe99cbc6000, 2097152, PROT_NONE) = 0
mmap(0x7fe99cdc6000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x18d000) = 0x7fe99cdc6000
mmap(0x7fe99cdcc000, 15768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fe99cdcc000
close(3)                                = 0
open("/lib64/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0p\16\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=14344, ...}) = 0
mmap(NULL, 2109712, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fe99c831000
mprotect(0x7fe99c833000, 2097152, PROT_NONE) = 0
mmap(0x7fe99ca33000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7fe99ca33000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe99d4a8000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe99d4a7000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe99d4a6000
arch_prctl(ARCH_SET_FS, 0x7fe99d4a7700) = 0
mprotect(0x7fe99cdc6000, 16384, PROT_READ) = 0
mprotect(0x7fe99ca33000, 4096, PROT_READ) = 0
mprotect(0x7fe99d028000, 16384, PROT_READ) = 0
mprotect(0x7fe99d271000, 8192, PROT_READ) = 0
mprotect(0x6a8000, 4096, PROT_READ)     = 0
mprotect(0x7fe99d4a3000, 4096, PROT_READ) = 0
munmap(0x7fe99d479000, 159933)          = 0
open("/dev/tty", O_RDWR|O_NONBLOCK)     = 3
close(3)                                = 0
brk(NULL)                               = 0x18d7000
brk(0x18f8000)                          = 0x18f8000
getuid()                                = 1000
getgid()                                = 1000
geteuid()                               = 1000
getegid()                               = 1000
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
sysinfo({uptime=275701, loads=[38944, 47392, 31936], totalram=12565557248, freeram=2656571392, sharedram=182452224, bufferram=1009516544, totalswap=536866816, freeswap=505884672, procs=873, totalhigh=0, freehigh=0, mem_unit=1}) = 0
rt_sigaction(SIGCHLD, {SIG_DFL, [], SA_RESTORER|SA_RESTART, 0x7fe99ca6c000}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGCHLD, {SIG_DFL, [], SA_RESTORER|SA_RESTART, 0x7fe99ca6c000}, {SIG_DFL, [], SA_RESTORER|SA_RESTART, 0x7fe99ca6c000}, 8) = 0
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7fe99ca6c000}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7fe99ca6c000}, {SIG_DFL, [], SA_RESTORER, 0x7fe99ca6c000}, 8) = 0
rt_sigaction(SIGQUIT, {SIG_DFL, [], SA_RESTORER, 0x7fe99ca6c000}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGQUIT, {SIG_DFL, [], SA_RESTORER, 0x7fe99ca6c000}, {SIG_DFL, [], SA_RESTORER, 0x7fe99ca6c000}, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigaction(SIGQUIT, {SIG_IGN, [], SA_RESTORER, 0x7fe99ca6c000}, {SIG_DFL, [], SA_RESTORER, 0x7fe99ca6c000}, 8) = 0
uname({sysname="Linux", nodename="pc125", ...}) = 0
stat("/home/jan", {st_mode=S_IFDIR|0700, st_size=12288, ...}) = 0
stat(".", {st_mode=S_IFDIR|0700, st_size=12288, ...}) = 0
getpid()                                = 26268
getppid()                               = 26266
getpgrp()                               = 26266
rt_sigaction(SIGCHLD, {0x42e2d0, [], SA_RESTORER|SA_RESTART, 0x7fe99ca6c000}, {SIG_DFL, [], SA_RESTORER|SA_RESTART, 0x7fe99ca6c000}, 8) = 0
getrlimit(RLIMIT_NPROC, {rlim_cur=47672, rlim_max=47672}) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
open("/usr/bin/ring", O_RDONLY)         = 3
ioctl(3, TCGETS, 0x7ffcce461840)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(3, 0, SEEK_CUR)                   = 0
read(3, "#!/bin/bash\n#\n#  Copyright (C) 2"..., 80) = 80
lseek(3, 0, SEEK_SET)                   = 0
getrlimit(RLIMIT_NOFILE, {rlim_cur=1024, rlim_max=4*1024}) = 0
fcntl(255, F_GETFD)                     = -1 EBADF (Bad file descriptor)
dup2(3, 255)                            = 255
close(3)                                = 0
fcntl(255, F_SETFD, FD_CLOEXEC)         = 0
fcntl(255, F_GETFL)                     = 0x8000 (flags O_RDONLY|O_LARGEFILE)
fstat(255, {st_mode=S_IFREG|0755, st_size=1608, ...}) = 0
lseek(255, 0, SEEK_CUR)                 = 0
read(255, "#!/bin/bash\n#\n#  Copyright (C) 2"..., 1608) = 1608
open("/dev/null", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
fcntl(1, F_GETFD)                       = 0
fcntl(1, F_DUPFD, 10)                   = 10
fcntl(1, F_GETFD)                       = 0
fcntl(10, F_SETFD, FD_CLOEXEC)          = 0
dup2(3, 1)                              = 1
close(3)                                = 0
open("/dev/null", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
fcntl(2, F_GETFD)                       = 0
fcntl(2, F_DUPFD, 10)                   = 11
fcntl(2, F_GETFD)                       = 0
fcntl(11, F_SETFD, FD_CLOEXEC)          = 0
dup2(3, 2)                              = 2
close(3)                                = 0
stat(".", {st_mode=S_IFDIR|0700, st_size=12288, ...}) = 0
stat("/usr/local/bin/ring-kde", 0x7ffcce461300) = -1 ENOENT (No such file or directory)
stat("/usr/bin/ring-kde", 0x7ffcce461300) = -1 ENOENT (No such file or directory)
stat("/bin/ring-kde", 0x7ffcce461300)   = -1 ENOENT (No such file or directory)
stat("/opt/bin/ring-kde", 0x7ffcce461300) = -1 ENOENT (No such file or directory)
stat("/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.4/ring-kde", 0x7ffcce461300) = -1 ENOENT (No such file or directory)
stat("/usr/lib64/subversion/bin/ring-kde", 0x7ffcce461300) = -1 ENOENT (No such file or directory)
fstat(2, {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 3), ...}) = 0
ioctl(2, TCGETS, 0x7ffcce460bf0)        = -1 ENOTTY (Inappropriate ioctl for device)
write(2, "/usr/bin/ring: line 25: type: ri"..., 50) = 50
dup2(11, 2)                             = 2
fcntl(11, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
close(11)                               = 0
dup2(10, 1)                             = 1
fcntl(10, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
close(10)                               = 0
open("/dev/null", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
fcntl(1, F_GETFD)                       = 0
fcntl(1, F_DUPFD, 10)                   = 10
fcntl(1, F_GETFD)                       = 0
fcntl(10, F_SETFD, FD_CLOEXEC)          = 0
dup2(3, 1)                              = 1
close(3)                                = 0
open("/dev/null", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
fcntl(2, F_GETFD)                       = 0
fcntl(2, F_DUPFD, 10)                   = 11
fcntl(2, F_GETFD)                       = 0
fcntl(11, F_SETFD, FD_CLOEXEC)          = 0
dup2(3, 2)                              = 2
close(3)                                = 0
stat(".", {st_mode=S_IFDIR|0700, st_size=12288, ...}) = 0
stat("/usr/local/bin/gnome-ring", 0x7ffcce461300) = -1 ENOENT (No such file or directory)
stat("/usr/bin/gnome-ring", {st_mode=S_IFREG|0755, st_size=1007672, ...}) = 0
stat("/usr/bin/gnome-ring", {st_mode=S_IFREG|0755, st_size=1007672, ...}) = 0
geteuid()                               = 1000
getegid()                               = 1000
getuid()                                = 1000
getgid()                                = 1000
access("/usr/bin/gnome-ring", X_OK)     = 0
stat("/usr/bin/gnome-ring", {st_mode=S_IFREG|0755, st_size=1007672, ...}) = 0
geteuid()                               = 1000
getegid()                               = 1000
getuid()                                = 1000
getgid()                                = 1000
access("/usr/bin/gnome-ring", R_OK)     = 0
stat("/usr/bin/gnome-ring", {st_mode=S_IFREG|0755, st_size=1007672, ...}) = 0
stat("/usr/bin/gnome-ring", {st_mode=S_IFREG|0755, st_size=1007672, ...}) = 0
geteuid()                               = 1000
getegid()                               = 1000
getuid()                                = 1000
getgid()                                = 1000
access("/usr/bin/gnome-ring", X_OK)     = 0
stat("/usr/bin/gnome-ring", {st_mode=S_IFREG|0755, st_size=1007672, ...}) = 0
geteuid()                               = 1000
getegid()                               = 1000
getuid()                                = 1000
getgid()                                = 1000
access("/usr/bin/gnome-ring", R_OK)     = 0
fstat(1, {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 3), ...}) = 0
ioctl(1, TCGETS, 0x7ffcce460c90)        = -1 ENOTTY (Inappropriate ioctl for device)
write(1, "gnome-ring is /usr/bin/gnome-rin"..., 34) = 34
dup2(11, 2)                             = 2
fcntl(11, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
close(11)                               = 0
dup2(10, 1)                             = 1
fcntl(10, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
close(10)                               = 0
stat(".", {st_mode=S_IFDIR|0700, st_size=12288, ...}) = 0
stat("/usr/local/bin/gnome-ring", 0x7ffcce4611b0) = -1 ENOENT (No such file or directory)
stat("/usr/bin/gnome-ring", {st_mode=S_IFREG|0755, st_size=1007672, ...}) = 0
stat("/usr/bin/gnome-ring", {st_mode=S_IFREG|0755, st_size=1007672, ...}) = 0
geteuid()                               = 1000
getegid()                               = 1000
getuid()                                = 1000
getgid()                                = 1000
access("/usr/bin/gnome-ring", X_OK)     = 0
stat("/usr/bin/gnome-ring", {st_mode=S_IFREG|0755, st_size=1007672, ...}) = 0
geteuid()                               = 1000
getegid()                               = 1000
getuid()                                = 1000
getgid()                                = 1000
access("/usr/bin/gnome-ring", R_OK)     = 0
stat("/usr/bin/gnome-ring", {st_mode=S_IFREG|0755, st_size=1007672, ...}) = 0
stat("/usr/bin/gnome-ring", {st_mode=S_IFREG|0755, st_size=1007672, ...}) = 0
geteuid()                               = 1000
getegid()                               = 1000
getuid()                                = 1000
getgid()                                = 1000
access("/usr/bin/gnome-ring", X_OK)     = 0
stat("/usr/bin/gnome-ring", {st_mode=S_IFREG|0755, st_size=1007672, ...}) = 0
geteuid()                               = 1000
getegid()                               = 1000
getuid()                                = 1000
getgid()                                = 1000
access("/usr/bin/gnome-ring", R_OK)     = 0
rt_sigprocmask(SIG_BLOCK, [INT CHLD], [], 8) = 0
lseek(255, -205, SEEK_CUR)              = 1403
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe99d4a79d0) = 26269
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigaction(SIGINT, {0x42b570, [], SA_RESTORER, 0x7fe99ca6c000}, {SIG_DFL, [], SA_RESTORER, 0x7fe99ca6c000}, 8) = 0
wait4(-1, gnome-ring: symbol lookup error: gnome-ring: undefined symbol: _ZN6Person9callAddedEP4Call
[{WIFEXITED(s) && WEXITSTATUS(s) == 127}], 0, NULL) = 26269
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7fe99ca6c000}, {0x42b570, [], SA_RESTORER, 0x7fe99ca6c000}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=26269, si_uid=1000, si_status=127, si_utime=2, si_stime=0} ---
wait4(-1, 0x7ffcce460d10, WNOHANG, NULL) = -1 ECHILD (No child processes)
rt_sigreturn({mask=[]})                 = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
exit_group(127)                         = ?
+++ exited with 127 +++

Any thoughts or suggestions on what this could be?

**Comment by stefan-langenmaier** [comment]
Hi josiah47,

which version of the ebuild have you been compiling? The live ebuilds? If yes have you recompiled also the dependencies like libringclient and ring-daemon.

If you used the versioned ebuilds, I don't really have an idea. Could you send the output of emerge --info. Are you using a very recent gcc or different libc? There was a recent update to glibc. Have you tried to just recompile gnome-ring?

Best regards
Stefan

**Comment by josiah47** [comment]
I am not using the live ebuilds, using the versioned, tried 20170119 again this morning.
I emerge -C all three packages first to make sure they were all 20170119
same error.
I could try the live i guess.

> Portage 2.3.0 (python 3.4.5-final-0, default/linux/amd64/13.0, gcc-4.9.4, glibc-2.23-r3, 4.4.6-gentoo x86_64)
=================================================================
System uname: Linux-4.4.6-gentoo-x86_64-AMD_FX-tm-4350_Quad-Core_Processor-with-gentoo-2.3
KiB Mem:    12271052 total,   4338184 free
KiB Swap:     524284 total,    430736 free
Timestamp of repository gentoo: Mon, 23 Jan 2017 06:00:01 +0000
sh bash 4.3_p48-r1
ld GNU ld (Gentoo 2.25.1 p1.1) 2.25.1
app-shells/bash:          4.3_p48-r1::gentoo
dev-java/java-config:     2.2.0-r3::gentoo
dev-lang/perl:            5.22.3_rc4::gentoo
dev-lang/python:          2.7.12::gentoo, 3.4.5::gentoo
dev-util/cmake:           3.6.3::gentoo
dev-util/pkgconfig:       0.28-r2::gentoo
sys-apps/baselayout:      2.3::gentoo
sys-apps/openrc:          0.22.4::gentoo
sys-apps/sandbox:         2.10-r1::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69::gentoo
sys-devel/automake:       1.11.6-r1::gentoo, 1.14.1::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            4.9.4::gentoo
sys-devel/gcc-config:     1.7.3::gentoo
sys-devel/libtool:        2.4.6-r2::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 4.4::gentoo (virtual/os-headers)
sys-libs/glibc:           2.23-r3::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://gentoo.portage.net/gentoo-portage
    priority: -1000

ring-overlay
    location: /var/lib/layman/ring-overlay
    masters: gentoo
    priority: 0

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=k8 -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/php/apache2-php5.6/ext-active/ /etc/php/cgi-php5.6/ext-active/ /etc/php/cli-php5.6/ext-active/ /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-march=k8 -O2 -pipe"
DISTDIR="/usr/portage/distfiles"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j9"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X acl alsa amd64 apache2 apng archive berkdb bzip2 cli cracklib crypt cups cxx dbus dri extras fat ffmpeg flac fortran fuse gdbm gdu gpm gtk gtkstyle iconv ieee1394 imagemagick ipv6 jabber jack java jpeg lame libnotify lm_sensors mmx modules mozilla mp3 mp4 mtp mysql ncurses nls nptl nsplugin ntfs ogg openal openmp opus pam pcre pdf php png policykit pulseaudio qt3support qt5 readline samba seccomp session sse sse2 ssl svg taglib tcpd threads thunar tiff udev unicode v4l v4l2 wavpack winbind x264 x265 xattr xfce xinerama xrandr zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx fma4 mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 xop" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="evdev void" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="wiki-publisher" LINGUAS="en" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7 python3_4" RUBY_TARGETS="ruby21" USERLAND="GNU" VIDEO_CARDS="nvidia" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LANG, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, USE_PYTHON

**Comment by stefan-langenmaier** [comment]
Sorry, I don't really have an idea. Looks all quite normal to me.

In your _CFLAGS_ I can see a _-march=k8_. Is this intentional?

**Comment by stefan-langenmaier** [comment]
Does the problem still exist?

**Comment by josiah47** [comment]
Yes this is till doing it this morning, after 
layman -S
and then recompiling gnome-ring version gnome-ring-20170223.1

might be linked to this part of the code, only reference that I can deduce from the cryptic message.
https://github.com/savoirfairelinux/ring-client-gnome/search?utf8=%E2%9C%93&q=Person%3A%3AcallAdded

**Comment by josiah47** [comment]
Also I am trying to test inside the docker build but get errors during the portage update on glibc
docker build -t ringcx -f docker/Dockerfile_gentoo .
running that from this extraction ring_20170223.1.0c6e5b2.tar.gz

**Comment by stefan-langenmaier** [comment]
I'm also currently trying to make it build in a Docker container. Do you have a sandbox violation with glibc. If yes you need to enable the PTRACE capability for your container or disable the sandbox of portage for the build.

**Comment by stefan-langenmaier** [comment]
Hi was talking to a ring developer:

> sim590:  slangen: it means you don't have the good LRC version for the client you compiled. The gnome client is lookfing for symbols it can't find in the binaries it's using. This may occur if you have for instance two diffrent versions installed on your system, for e.g. /usr/ /usr/local and one over shadows the other in priority. That's my understanding.

Can you do `ldd /usr/bin/gnome-ring` and check the path for the `libringclient.so`?

Is this file replaced if you do an install of libringclient?

**Comment by stefan-langenmaier** [comment]
Have you had a chance to verify this?

**Comment by josiah47** [comment]
Terribly sorry,  forgot about this and started to use ring on android, so updated my packages and it was doing it again but this time

> gnome-ring: symbol lookup error: gnome-ring: undefined symbol: _ZNK3lrc3api17ConversationModel19conversationUpdatedERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

so i deleted all libringclient.so on my system and recompiled and it works!

Thank you for your time and effort on this.

**Comment by stefan-langenmaier** [comment]
No worries, feedback is always welcome!
