### ISSUE TITLE
net-libs/restbed: ebuild update, new deps added

### ISSUE THREAD

**Issue by YogSottot** [stefan-langenmaier/ring-overlay#20]
https://github.com/reagentoo/gentoo-overlay/commit/d77fc1cc6fd156cae55caaf9b2014f38483a83a7

```
RDEPEND="
	>=dev-cpp/asio-1.10
	dev-cpp/kashmir
	sys-libs/zlib
	examples? (
		sys-libs/pam
		virtual/logger
	)
	ssl? ( dev-libs/openssl )
	test? ( dev-cpp/catch )
"
```
May be you want to merge this commit?

**Comment by stefan-langenmaier** [comment]
The commit that is pulled in the current restbed-4.5.ebuild is not actually the 4.5 version as it is not released yet. I think it's a commit that does not yet need the kashmir dependency. So I would avoid touching that ebuild. But I think the live version could already be updated.
