### ISSUE TITLE
net-voip/ring-daemon-20170223.1 - Fetched file: ring_20170223.1.0c6e5b2.tar.gz VERIFY FAILED

### ISSUE THREAD

**Issue by anonymous09** [stefan-langenmaier/ring-overlay#31]
Hi! net-voip/ring-daemon-20170223.1 build fails.
```
!!! Fetched file: ring_20170223.1.0c6e5b2.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      195432476
!!! Expected: 195432913
```

**Comment by stefan-langenmaier** [comment]
Hi! Thanks for your feedback.
Have you tried to redownload the file?
Anyway I'll check it tonight.

**Comment by anonymous09** [comment]
Yes, I tried few times. Also, github can't attach build.log or zipped/gzipped build.log. So, here it http://dump.bitcheese.net/files/cabasoj/build.log.gz

**Comment by stefan-langenmaier** [comment]
Well with my previously downloaded file I don't have the problem. I redownloaded it and I can confirm the issue.
There is already a newer version available and I think I will have it packaged by tomorrow. So I think I won't fix this and go straight to the next version. I'll leave this issue open until the new version is out.

**Comment by stefan-langenmaier** [comment]
I pushed a newer version. This should solve the problem.
