### ISSUE TITLE
kde-ring fails to compile

### ISSUE THREAD

**Issue by stikonas** [stefan-langenmaier/ring-overlay#33]
>>> Emerging (1 of 1) net-voip/kde-ring-99999999::ring-overlay                                                                                                                                                    
>>> Unpacking source...                                                                                                                                                                                           
Initialized empty Git repository in /usr/portage/distfiles/git3-src/ring-kde.git/                                                                                                                                 
 * Fetching git://anongit.kde.org/ring-kde ...                                                                                                                                                                    
git fetch git://anongit.kde.org/ring-kde +HEAD:refs/git-r3/HEAD                                                                                                                                                   
remote: Counting objects: 20294, done.
remote: Compressing objects: 100% (2959/2959), done.
remote: Total 20294 (delta 17361), reused 20177 (delta 17268)
Receiving objects: 100% (20294/20294), 7.13 MiB | 2.01 MiB/s, done.                                                                                                                                               
Resolving deltas: 100% (17361/17361), done.                                                                                                                                                                       
From git://anongit.kde.org/ring-kde                                                                                                                                                                               
 * [new ref]                      -> refs/git-r3/HEAD
 * [new tag]           1.2.0      -> 1.2.0
 * [new tag]           1.3.0      -> 1.3.0
 * [new tag]           1.4.0      -> 1.4.0
 * [new tag]           1.4.1      -> 1.4.1
 * [new tag]           2.0.0      -> 2.0.0
git symbolic-ref refs/git-r3/net-voip/kde-ring/0/__main__ refs/git-r3/HEAD
 * Checking out git://anongit.kde.org/ring-kde to /var/tmp/portage/net-voip/kde-ring-99999999/work/kde-ring-99999999 ...
git checkout --quiet refs/git-r3/HEAD
GIT NEW branch -->
   repository:               git://anongit.kde.org/ring-kde
   at the commit:            de9cc2fea7480c3f2d706809860ad3954e6d6d9d
>>> Source unpacked in /var/tmp/portage/net-voip/kde-ring-99999999/work
>>> Preparing source in /var/tmp/portage/net-voip/kde-ring-99999999/work/kde-ring-99999999 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/net-voip/kde-ring-99999999/work/kde-ring-99999999 ...
>>> Working in BUILD_DIR: "/var/tmp/portage/net-voip/kde-ring-99999999/work/kde-ring-99999999_build"
cmake -C /var/tmp/portage/net-voip/kde-ring-99999999/work/kde-ring-99999999_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_VIDEO=true -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_USER_MAKE_RULES_OVERRIDE=/var/tmp/portage/net-voip/kde-ring-99999999/work/kde-ring-99999999_build/gentoo_rules.cmake -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/net-voip/kde-ring-99999999/work/kde-ring-99999999_build/gentoo_toolchain.cmake  /var/tmp/portage/net-voip/kde-ring-99999999/work/kde-ring-99999999
loading initial cache file /var/tmp/portage/net-voip/kde-ring-99999999/work/kde-ring-99999999_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LIB_RING_CLIENT: /usr/lib64/libringclient.so  
-- Found Git: /usr/bin/git (found version "2.13.0") 
-- Downloading the GNU Ring API definition
-- Fetching Ring-LRC from GitHub
Cloning into '/var/tmp/portage/net-voip/kde-ring-99999999/work/kde-ring-99999999_build/ring-lrc'...
CMake Error at cmake/FetchRing-LRC.cmake:76 (ADD_SUBDIRECTORY):
  add_subdirectory not given a binary directory but the given source
  directory
  "/var/tmp/portage/net-voip/kde-ring-99999999/work/kde-ring-99999999_build/ring-lrc"
  is not a subdirectory of
  "/var/tmp/portage/net-voip/kde-ring-99999999/work/kde-ring-99999999".  When
  specifying an out-of-tree source a binary directory must be explicitly
  specified.
Call Stack (most recent call first):
  CMakeLists.txt:32 (INCLUDE)

-- Installing in the same prefix as Qt, adopting their path scheme.
-- Could not set up the appstream test. appstreamcli is missing.
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Found GCC version >= 4.8: 6.3.0

-- Found KF5Config: /usr/lib64/cmake/KF5Config/KF5ConfigConfig.cmake (found version "5.34.0") 
-- Found KF5GuiAddons: /usr/lib64/cmake/KF5GuiAddons/KF5GuiAddonsConfig.cmake (found version "5.34.0") 
-- Found KF5DBusAddons: /usr/lib64/cmake/KF5DBusAddons/KF5DBusAddonsConfig.cmake (found version "5.34.0") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
-- Found PythonInterp: /usr/bin/python (found version "3.4.5") 
-- Found KF5I18n: /usr/lib64/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.34.0") 
-- Found KF5Init: /usr/lib64/cmake/KF5Init/KF5InitConfig.cmake (found version "5.34.0") 
-- Found KF5WindowSystem: /usr/lib64/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (found version "5.34.0") 
-- Found KF5XmlGui: /usr/lib64/cmake/KF5XmlGui/KF5XmlGuiConfig.cmake (found version "5.34.0") 
-- Found KF5Notifications: /usr/lib64/cmake/KF5Notifications/KF5NotificationsConfig.cmake (found version "5.34.0") 
-- Found KF5IconThemes: /usr/lib64/cmake/KF5IconThemes/KF5IconThemesConfig.cmake (found version "5.34.0") 
-- Found KF5KIO: /usr/lib64/cmake/KF5KIO/KF5KIOConfig.cmake (found version "5.34.0") 
-- Found KF5Completion: /usr/lib64/cmake/KF5Completion/KF5CompletionConfig.cmake (found version "5.34.0") 
-- Found KF5Crash: /usr/lib64/cmake/KF5Crash/KF5CrashConfig.cmake (found version "5.34.0") 
-- Found KF5NotifyConfig: /usr/lib64/cmake/KF5NotifyConfig/KF5NotifyConfigConfig.cmake (found version "5.34.0") 
-- Found KF5GlobalAccel: /usr/lib64/cmake/KF5GlobalAccel/KF5GlobalAccelConfig.cmake (found version "5.34.0") 
-- Found KF5: success (found suitable version "5.34.0", minimum required is "5.6.0") found components:  Config GuiAddons DBusAddons I18n Init WindowSystem XmlGui Notifications IconThemes KIO Completion Crash NotifyConfig GlobalAccel 
-- Found KF5Akonadi: /usr/lib64/cmake/KF5Akonadi/KF5AkonadiConfig.cmake (found version "5.5.2") 
-- Found KF5AkonadiContact: /usr/lib64/cmake/KF5AkonadiContact/KF5AkonadiContactConfig.cmake (found version "5.5.2") 
-- Found KF5Contacts: /usr/lib64/cmake/KF5Contacts/KF5ContactsConfig.cmake (found version "5.5.2") 
-- Found KF5: success (found suitable version "5.34.0", minimum required is "5.6.0") found components:  KIO I18n GuiAddons 
-- Could not set up the appstream test. appstreamcli is missing.
-- Found KF5WidgetsAddons: /usr/lib64/cmake/KF5WidgetsAddons/KF5WidgetsAddonsConfig.cmake (found version "5.34.0") 
-- Found KF5: success (found version "5.34.0") found components:  Config GuiAddons I18n Init WindowSystem WidgetsAddons XmlGui 
-- <<< Gentoo configuration >>>
Build type      Gentoo
Install path    /usr
Compiler flags:
C               -march=native -O2 -pipe -std=iso9899:1990 -fno-common -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wmissing-format-attribute -Wwrite-strings -Werror=implicit-function-declaration
C++             -march=native -O2 -pipe -std=c++0x -fno-operator-names -fno-exceptions -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Wvla -Wdate-time
Linker flags:
Executable      -Wl,--enable-new-dtags -march=native -O2 -pipe
Module          -Wl,--no-undefined -Wl,--fatal-warnings -Wl,--enable-new-dtags -march=native -O2 -pipe
Shared          -Wl,--no-undefined -Wl,--fatal-warnings -Wl,--enable-new-dtags -march=native -O2 -pipe

-- Configuring incomplete, errors occurred!
See also "/var/tmp/portage/net-voip/kde-ring-99999999/work/kde-ring-99999999_build/CMakeFiles/CMakeOutput.log".

**Comment by stefan-langenmaier** [comment]
Thanks for your feedback. I try to look into it on the weekend.

**Comment by stefan-langenmaier** [comment]
I can reproduce the problem but I have difficulties spotting what the actual error is.

**Comment by YogSottot** [comment]
You can fix it by adding 
```
CMAKE_IN_SOURCE_BUILD="true"
```
I already bypass this problem in this  [branch](https://github.com/YogSottot/ring-overlay/blob/kde-ring/net-voip/kde-ring/kde-ring-99999999.ebuild), but met another problems, so I did not make a PR
YogSottot/ring-overlay#9
YogSottot/ring-overlay#10

**Comment by stefan-langenmaier** [comment]
@YogSottot thanks for your input. I also tried to switch to the "next" branch, but I had some compile errors that wanted a newer version of Qt (>=5.7). It would be nice to keep me posted when you have gotten figured it out. :)

**Comment by stikonas** [comment]
Well, Qt 5.7 should be fine soon. There is already a stabilization request for 5.7.1.

**Comment by YogSottot** [comment]
I'm switched to qtcore 5.7 long time ago. So i didn't aware about those errors.
Right now it is possible to build a binary package kde-ring-next, then remove libringclient and install kde-ring. A very hackish way.

**Comment by stefan-langenmaier** [comment]
It is probably no error/problem, but I'm mostly on a stable system and didn't want to figure out all the packages I have to keyword. :)

**Comment by stefan-langenmaier** [comment]
Thanks for all the feedback on kde-ring, I'll try to look into it on the weekend.

**Comment by stefan-langenmaier** [comment]
Thanks to all the work of @YogSottot there is now again a kde-ring package that compiles. The live ebuild is still a work in progress.
