### ISSUE TITLE
net-voip/ring-daemon-20170803.2 fails to compile : missing Argon2

### ISSUE THREAD

**Issue by njuneau** [stefan-langenmaier/ring-overlay#38]
Hello Stefan,

I hope you are doing well! I tried to update to Ring 1.0 this morning and the ebuild failed at the configure phase with the following error:

`configure: error: Missing Argon2`

Here's the econf line:

`'--without-opensl' '--with-alsa' '--with-dbus' '--with-gsm' '--without-jack' '--with-libilbc' '--with-natpmp' '--with-opus' '--without-portaudio' '--with-puls' '--without-restcpp' '--with-sdes' '--with-speex' '--with-speexdsp' '--with-upnp' '--enable-doxygen' '--enable-dot' '--enable-accel' '--enable-ipv6' '--enable-ringns' '--enable-vaapi' '--enable-video'`

Do you have a similar issue on your end?

Thanks!

**Comment by stefan-langenmaier** [comment]
Salut Nicolas,

at the moment the bundled version of argon2 should be used again. Someone had this problem recently (#34) and I already created a reminder to fix it (#35). So no, I didn't have the problem when I built the package locally. Maybe you still have the argon2 package installed and this is confusing the build system.

I will have a closer look for what's the current state with the argon2 dep this week.

Thanks for the information et donne le bonjour à tout le monde!

**Comment by YogSottot** [comment]
>  Someone had this problem recently (#34)
This fix has been removed from this overlay, so the problem reappeared. The fix still works for me in my local overlay.

**Comment by njuneau** [comment]
Hello Stefan,

With the new ebuild revision (20170803.2-r1), the daemon compiles just fine with our without system-pjproject. In all cases, Argon2 is found.

In my case, there's no longer an issue here. @YogSottot do you still have the problem?

**Comment by YogSottot** [comment]
> In all cases, Argon2 is found

It was fixed again in [this commit ](https://github.com/stefan-langenmaier/ring-overlay/commit/0a493245ea83433dcb991fab7899ea80813a3314)
