### ISSUE TITLE
net-voip/kde-ring-99999999::ring-overlay has file collisions with net-libs/libringclient-20170803.2-r1:0::ring-overlay

### ISSUE THREAD

**Issue by martijn-schmidt** [stefan-langenmaier/ring-overlay#40]
Hey all,

Please reference the attached build.log from net-voip/kde-ring-99999999::ring-overlay - as you can see, it compiles all the way and then fails during the install phase due to file collisions with net-libs/libringclient-20170803.2-r1:0::ring-overlay as seen at the end of the file.

[build.log.txt](https://github.com/stefan-langenmaier/ring-overlay/files/1232640/build.log.txt)

Most probably, libringclient should provide these files and kde-ring simply needs to reference them as a dependency. I wasn't able to figure out on my own how to stop kde-ring from installing these files.

Best regards,
Martijn Schmidt

**Comment by stefan-langenmaier** [comment]
There is now a snapshot ebuild of kde-ring. It's blocking libringclient so you can no longer have gnome-ring and kde-ring installed at the same time. This is not a perfect situation, but the live ebuild is still a work in progress.

**Comment by YogSottot** [comment]
https://bugs.kde.org/show_bug.cgi?id=383718

Upstream is closed this bug as RESOLVED FIXED

**Comment by stefan-langenmaier** [comment]
Thanks for the follow up!

This will still need a major package update as there has no work on the ebuild in a long time.
