### ISSUE TITLE
=net-libs/libringclient-20180216.1 fails to build

### ISSUE THREAD

**Issue by netfab** [stefan-langenmaier/ring-overlay#45]
Hi,

[libringclient-20180216.1:20180223-124346.log](https://github.com/stefan-langenmaier/ring-overlay/files/1751731/libringclient-20180216.1.20180223-124346.log)

Thanks.

**Comment by stefan-langenmaier** [comment]
Hi netfab,

thanks for your feedback.

The problem seems to be a missing dependency on qtsql. The dependencies in the ebuild should contain a line like ">=dev-qt/qtsql-5".
Would you like to do a pull request? Otherwise I have a look into it on the weekend.

Have a nice day!
Stefan
