### ISSUE TITLE
net-voip/ring-daemon building without pulseaudio support

### ISSUE THREAD

**Issue by steils** [stefan-langenmaier/ring-overlay#53]
net-voip/ring-daemon turns on 'pulseaudio' by default (IUSE="+pulseaudio"). Is it really needed? ring-daemon successfully builds with -pulseaudio, but I have to explicitly set USE="-pulseaudio" for net-voip/ring-daemon.
Shouldn't it be just IUSE="pulseaudio"?

**Comment by stefan-langenmaier** [comment]
I have no strong opinion on pulseaudio. I'll remove the default as you suggested and we'll see if someone complains.
