### ISSUE TITLE
dev-libs/msgpack not building with gcc-8.2

### ISSUE THREAD

**Issue by KuroLevin** [stefan-langenmaier/ring-overlay#57]
Seems like a new warning by gcc-8.2 that becomes an error with -Werror.
The build log is available in the attachment
[build-abi_x86_64.amd64.log](https://github.com/stefan-langenmaier/ring-overlay/files/2315043/build-abi_x86_64.amd64.log)

.

**Comment by KuroLevin** [comment]
That version does build but there is also a similar bug open for the latest unmasked version with gcc7: 
https://bugs.gentoo.org/show_bug.cgi?id=658262.
The problem seems to be referred [here](https://devmanual.gentoo.org/ebuild-writing/common-mistakes/) and the solution should apply to booth versions.

**Comment by stefan-langenmaier** [comment]
I will look into the option to remove the version in this repo if it isn't needed.

The issue in the bugzilla is referencing an earlier version (1.2.0). I leave the issue open for the moment.

**Comment by KuroLevin** [comment]
After digging deeper i found out that upstream from version 1.4.2 onward a patch is applied that removes the Werror flag. Haven't checked if the patch is compatible with the version in here but it should be.

**Comment by stefan-langenmaier** [comment]
Seems to be fixed: https://bugs.gentoo.org/658262
