### ISSUE TITLE
Missing dependency in net-voip/gnome-ring

### ISSUE THREAD

**Issue by KuroLevin** [stefan-langenmaier/ring-overlay#58]
cmake fails with a message that libcanberra-gtk3>=0.25 is missing.
Installing the media-libs/libcanberra package with the gtk3 use flag solves the issue so it should be probably added as a dependency.

**Comment by stefan-langenmaier** [comment]
Thanks for the feedback. I'll try to include it on the weekend.

**Comment by stefan-langenmaier** [comment]
I pushed a newer version and added the dependency. That should solve the issue.
