### ISSUE TITLE
net-libs/restbed-4.6 requires  dev-cpp/asio-1.12.2 to build properly 

### ISSUE THREAD

**Issue by 0k00l** [stefan-langenmaier/ring-overlay#66]
Mask it in portage mask:
`>dev-cpp/asio-1.12.0`
otherwise
`[ 90%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/web_socket_impl.cpp.o
/usr/bin/x86_64-pc-linux-gnu-g++ -DBUILD_SSL=TRUE -Drestbed_EXPORTS -I/var/tmp/portage/net-libs/restbed-4.6/work/restbed-4.6/source   -DNDEBUG -O3 -pipe -march=corei7 -mtune=corei7 -Wno-non-virtual-dtor -std=c++11 -O2 -Wall -Wextra -Weffc++ -pedantic -Wno-unknown-pragmas -pthread -DASIO_STANDALONE=YES -fPIC   -o CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/web_socket_impl.cpp.o -c /var/tmp/portage/net-libs/restbed-4.6/work/restbed-4.6/source/corvusoft/restbed/detail/web_socket_impl.cpp
/var/tmp/portage/net-libs/restbed-4.6/work/restbed-4.6/source/corvusoft/restbed/detail/socket_impl.cpp: In constructor ‘restbed::detail::SocketImpl::SocketImpl(const std::shared_ptr<asio::basic_stream_socket<asio::ip::tcp> >&, const std::shared_ptr<restbed::Logger>&)’:
/var/tmp/portage/net-libs/restbed-4.6/work/restbed-4.6/source/corvusoft/restbed/detail/socket_impl.cpp:54:65: error: ‘using element_type = class asio::basic_stream_socket<asio::ip::tcp>’ {aka ‘class asio::basic_stream_socket<asio::ip::tcp>’} has no member named ‘get_io_service’
   54 |             m_timer( make_shared< asio::steady_timer >( socket->get_io_service( ) ) ),
      |                                                                 ^~~~~~~~~~~~~~
/var/tmp/portage/net-libs/restbed-4.6/work/restbed-4.6/source/corvusoft/restbed/detail/socket_impl.cpp:55:67: error: ‘using element_type = class asio::basic_stream_socket<asio::ip::tcp>’ {aka ‘class asio::basic_stream_socket<asio::ip::tcp>’} has no member named ‘get_io_service’
   55 |             m_strand( make_shared< io_service::strand > ( socket->get_io_service( ) ) ),
      |                                                                   ^~~~~~~~~~~~~~
/var/tmp/portage/net-libs/restbed-4.6/work/restbed-4.6/source/corvusoft/restbed/detail/socket_impl.cpp: In constructor ‘restbed::detail::SocketImpl::SocketImpl(const std::shared_ptr<asio::ssl::stream<asio::basic_stream_socket<asio::ip::tcp> > >&, const std::shared_ptr<restbed::Logger>&)’:
/var/tmp/portage/net-libs/restbed-4.6/work/restbed-4.6/source/corvusoft/restbed/detail/socket_impl.cpp:70:81: error: ‘asio::ssl::stream<asio::basic_stream_socket<asio::ip::tcp> >::lowest_layer_type’ {aka ‘class asio::basic_socket<asio::ip::tcp, asio::executor>’} has no member named ‘get_io_service’
   70 |             m_timer( make_shared< asio::steady_timer >( socket->lowest_layer( ).get_io_service( ) ) ),
      |                                                                                 ^~~~~~~~~~~~~~
/var/tmp/portage/net-libs/restbed-4.6/work/restbed-4.6/source/corvusoft/restbed/detail/socket_impl.cpp:71:67: error: ‘using element_type = class asio::ssl::stream<asio::basic_stream_socket<asio::ip::tcp> >’ {aka ‘class asio::ssl::stream<asio::basic_stream_socket<asio::ip::tcp> >’} has no member named ‘get_io_service’
   71 |             m_strand( make_shared< io_service::strand > ( socket->get_io_service( ) ) ),
      |                                                                   ^~~~~~~~~~~~~~
/var/tmp/portage/net-libs/restbed-4.6/work/restbed-4.6/source/corvusoft/restbed/detail/socket_impl.cpp: In member function ‘void restbed::detail::SocketImpl::connect(const string&, uint16_t, const std::function<void(const std::error_code&)>&)’:
/var/tmp/portage/net-libs/restbed-4.6/work/restbed-4.6/source/corvusoft/restbed/detail/socket_impl.cpp:122:72: error: ‘using element_type = class asio::basic_stream_socket<asio::ip::tcp>’ {aka ‘class asio::basic_stream_socket<asio::ip::tcp>’} has no member named ‘get_io_service’
  122 |             auto& io_service = ( m_socket not_eq nullptr ) ? m_socket->get_io_service( ) : m_ssl_socket->lowest_layer( ).get_io_service( );
      |                                                                        ^~~~~~~~~~~~~~
/var/tmp/portage/net-libs/restbed-4.6/work/restbed-4.6/source/corvusoft/restbed/detail/socket_impl.cpp:122:122: error: ‘asio::ssl::stream<asio::basic_stream_socket<asio::ip::tcp> >::lowest_layer_type’ {aka ‘class asio::basic_socket<asio::ip::tcp, asio::executor>’} has no member named ‘get_io_service’
  122 |             auto& io_service = ( m_socket not_eq nullptr ) ? m_socket->get_io_service( ) : m_ssl_socket->lowest_layer( ).get_io_service( );
      |                                                                                                                          ^~~~~~~~~~~~~~
/var/tmp/portage/net-libs/restbed-4.6/work/restbed-4.6/source/corvusoft/restbed/detail/service_impl.cpp: In member function ‘void restbed::detail::ServiceImpl::http_listen() const’:
/var/tmp/portage/net-libs/restbed-4.6/work/restbed-4.6/source/corvusoft/restbed/detail/service_impl.cpp:150:67: error: ‘using element_type = class asio::basic_socket_acceptor<asio::ip::tcp>’ {aka ‘class asio::basic_socket_acceptor<asio::ip::tcp>’} has no member named ‘get_io_service’
  150 |             auto socket = make_shared< tcp::socket >( m_acceptor->get_io_service( ) );
      |                                                                   ^~~~~~~~~~~~~~
/var/tmp/portage/net-libs/restbed-4.6/work/restbed-4.6/source/corvusoft/restbed/detail/service_impl.cpp: In member function ‘void restbed::detail::ServiceImpl::https_listen() const’:
/var/tmp/portage/net-libs/restbed-4.6/work/restbed-4.6/source/corvusoft/restbed/detail/service_impl.cpp:276:92: error: ‘using element_type = class asio::basic_socket_acceptor<asio::ip::tcp>’ {aka ‘class asio::basic_socket_acceptor<asio::ip::tcp>’} has no member named ‘get_io_service’
  276 |             auto socket = make_shared< asio::ssl::stream< tcp::socket > >( m_ssl_acceptor->get_io_service( ), *m_ssl_context );
      |                                                                                            ^~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/restbed.dir/build.make:275: CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/socket_impl.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/restbed.dir/build.make:288: CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/service_impl.cpp.o] Error 1
make[2]: Leaving directory '/var/tmp/portage/net-libs/restbed-4.6/work/restbed-4.6_build'
make[1]: *** [CMakeFiles/Makefile2:93: CMakeFiles/restbed.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/net-libs/restbed-4.6/work/restbed-4.6_build'
make: *** [Makefile:147: all] Error 2
`
will occur

**Comment by stefan-langenmaier** [comment]
Hi @0k00l ,

thanks for your feedback, for now I fixed it in the latest tarball release with specifying the dependency version directly in the ebuild.

Best regards,
Stefan
