### ISSUE TITLE
net-voip/ring-daemon-20191110.1: No rule to make target '.dep-msgpack'

### ISSUE THREAD

**Issue by tastytea** [stefan-langenmaier/ring-overlay#67]
The build fails with:

```
make: *** No rule to make target '.dep-msgpack', needed by '.opendht'.  Stop.
```

USE="alsa dbus gsm hwaccel ipv6 libilbc nat-pmp opus pulseaudio ringns sdes speex speexdsp upnp vaapi vdpau video vpx x264 -doc -graph -jack (-libav) -portaudio -restbed -system-pjproject"

[build.log](https://github.com/stefan-langenmaier/ring-overlay/files/4475931/build.log) 
[emerge --info.txt](https://github.com/stefan-langenmaier/ring-overlay/files/4475943/emerge.--info.txt)

**Comment by stefan-langenmaier** [comment]
Thanks for the bug report. I couldn't reproduce it but I also have `dev-libs/msgpack` already installed. I added it as an explicit dependency. Let me know if this works for you.

**Comment by tastytea** [comment]
I got a bit further. 🙂

I now get this error:

```
jamiaccount.cpp: In member function ‘void jami::JamiAccount::doRegister_()’:                          
jamiaccount.cpp:1668:16: error: ‘struct dht::DhtRunner::Config’ has no member named ‘push_token’      
 1668 |         config.push_token = deviceKey_;                                                       
      |                ^~~~~~~~~~                                                                     
jamiaccount.cpp:1675:28: error: ‘struct dht::DhtRunner::Config’ has no member named ‘push_token’      
 1675 |             if (not config.push_token.empty()) {                                              
      |                            ^~~~~~~~~~                                                         
jamiaccount.cpp:1703:57: error: no match for ‘operator=’ (operand types are ‘std::unique_ptr<dht::Logg
er>’ and ‘std::shared_ptr<dht::Logger>’)                                                              
 1703 |                 (dht_log_level > 2) ? log_debug : silent);
```

[build.log](https://github.com/stefan-langenmaier/ring-overlay/files/4477078/build.log)

**Comment by stefan-langenmaier** [comment]
Is it possible `opendht` is still installed. If yes, please let me know, it should be uninstalled.

**Comment by tastytea** [comment]
Yes, it was installed. After I uninstalled it, ring-daemon builds now successfully. Thank you!

**Comment by stefan-langenmaier** [comment]
Thanks for your feedback!
